distributable:
  url: https://mesa.freedesktop.org/archive/mesa-{{version}}.tar.gz
  strip-components: 1

versions:
  url: https://archive.mesa3d.org/
  match: /mesa-\d+\.\d+\.\d+\.tar\.gz/
  strip:
    - /^mesa-/
    - /\.tar\.gz$/

dependencies:
  libexpat.github.io: '*'
  x.org/x11: '*'
  x.org/xcb: '*'
  x.org/xdamage: '*'
  x.org/exts: '*'
  invisible-island.net/ncurses: '*'
  zlib.net: '*'
  gnu.org/gettext: '*'
  linux:
    elfutils.org: '*'
    #khronos.org/opengles/sdk/tools/Reference-Compiler: '*'
    libzip.org: '*'
    dri.freedesktop.org: '*'
    #github.com/intel/libva: '*'
    #freedesktop.org/wiki/Software/VDPAU: '*'
    x.org/xfixes: '*'
    x.org/xrandr: '*'
    x.org/xshmfence: '*'
    x.org/xv: '*'
    x.org/xxf86vm: '*'
    llvm.org: '*'
    #github.com/lm-sensors/lm-sensors: '*'
    wayland.freedesktop.org: '*'
    wayland.freedesktop.org/protocols: '*'

build:
  dependencies:
    cmake.org: '*'
    gnu.org/gcc: '*'
    tea.xyz/gx/make: '*'
    gnu.org/bison: '*'
    mesonbuild.com: '*'
    ninja-build.org: '*'
    freedesktop.org/pkg-config: '*'
    pygments.org: '*'
    python.org: ^3.11
    x.org/protocol: '*'
    github.com/westes/flex: '*'
    pip.pypa.io: '*'
  
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install mako
    - deactivate
    - export PYTHONPATH=$PWD/venv/lib/python3.11/site-packages/markupsafe:$PWD/venv/lib/python3.11/site-packages/mako:$PYTHONPATH
    #- export PYTHONHOME=''
    #- export PYTHONPATH=''
    - meson setup build $ARGS
    - meson compile -C build --verbose
    - meson install -C build

  env:
    #PATH: "$PWD/venv/bin:$PATH"
    ARGS:
      - -Db_ndebug=true
      - --prefix={{prefix}}
      - --libdir=lib
      - --buildtype=release
      - --wrap-mode=nofallback
    linux:
      ARGS:
        - -Dplatforms=x11,wayland
        - -Dglx=auto
        - -Ddri3=true
        - -Dgallium-drivers=auto
        - -Dgallium-omx=disabled
        - -Degl=false
        - -Dgbm=true
        - -Dopengl=true
        - -Dgles1=true
        - -Dgles2=true
        - -Dvalgrind=false
        - -Dtools=etnaviv,freedreno,glsl,nir,nouveau

provides:
  - bin/foo
  # ^^ specify the binaries or tea magic won’t work

test:
  dependencies:
    foo.com: '*'  # asterisk means “any version, usually the latest”
  script:
    test "$(foo --version)" = {{version}}
    # if it’s a tool check the version matches
    # you should run the tool to check it works!
    # if it's a library then you should *use* the library
    # don’t forget to check other package.ymls in the pantry for examples!
