distributable:
  url: https://github.com/casey/just/archive/refs/tags/{{version}}.tar.gz
  strip-components: 1

versions:
  github: casey/just/tags
  strip: /v/

build:
  dependencies:
    rust-lang.org: ^1.47.0
    rust-lang.org/cargo: ^0.66
  script:
    # https://github.com/casey/just/issues/1898
    - sed -i 's/env_logger = "0.11.0"/env_logger = "0.10.0"/' Cargo.toml
    - cargo install --path=. --root={{prefix}}
  test: cargo test

test:
  script: |
    cp $FIXTURE justfile
    just
  fixture: |
    # run just -l
    default:
      @just -l

provides:
  - bin/just
