distributable:
  url: https://github.com/Peltoche/lsd/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

provides:
  - bin/lsd

versions:
  github: Peltoche/lsd/tags

dependencies:
  libgit2.org: ~1.7

build:
  dependencies:
    rust-lang.org: '>=1.60'
    rust-lang.org/cargo: '*'
  script: cargo install --path . --root {{prefix}}

test: test "$(lsd --oneline)" = "xyz.tea.test.sh"
